name = "pastebin-worker"
compatibility_date = "2023-10-30"
compatibility_flags = ["nodejs_compat"]

account_id = "516d0a360ccdea88dd79e9cf5d2bc3aa"
main = "src/index.ts"
workers_dev = false

[vars]
ENVIRONMENT = "production"
BASE_URL = "https://paste.sekka.fun"

[site]
bucket = "./static/dist"

# 如果不使用自定义域名，将下面的代码注释掉
[[routes]]
pattern = "as.al"
custom_domain = true

[[r2_buckets]]
binding = 'BUCKET'
bucket_name = "pastes"

[[d1_databases]]
binding = "DB"
database_name = "pastebins"
database_id = "c7a5cbc3-cbaa-40ae-853e-14e73f323b9a"
